-- Samain nama & satuan produk sesuai template Stock Opname DC B
-- (item yang confident/jelas cocok aja, sisanya perlu konfirmasi manual)

update items set nama='Beef Patties', satuan='pcs' where nama='Beef Patties';
update items set nama='Mix Vegetable', satuan='pack' where nama='Mix Vegetable';
update items set nama='Kardus Big Order', satuan='pcs' where nama='Kardus';
update items set nama='Sambal 500gr (new)', satuan='pack' where nama='Sambal';
update items set nama='Minyak Beku 15kg', satuan='carton' where nama='Minyak Beku';
update items set nama='Sup Krim Ayam', satuan='pack' where nama='Sup Cream';
update items set nama='Sarung Tangan Plastik', satuan='pack' where nama='Hand Glove';
update items set nama='Sealer Cup', satuan='Roll' where nama='Cup Sealer';
update items set nama='Kertas Struk Thermal', satuan='Roll' where nama='Thermal';
update items set nama='Polaris Kaleng', satuan='pcs' where nama='Polaris';
update items set nama='Beras Kebuli', satuan='ltr' where nama='Beras Kebuli';
update items set nama='Kertas Nasi 1000s', satuan='pack' where nama='Kertas Nasi';
update items set nama='Box Almaz', satuan='carton' where nama='Box Almaz';
update items set nama='Beras Putih', satuan='kg' where nama='Beras Putih';
update items set nama='Lemon Tea Powder', satuan='pack' where nama='Lemon Tea';
update items set nama='Cup Ice Cream', satuan='pack' where nama='Cup Ice';
update items set nama='Paper Bowl Almaz', satuan='pack' where nama='Paper Bowl';
update items set nama='Jinten', satuan='kg' where nama='Jinten';
update items set nama='Ajinomoto 1 kg', satuan='pack' where nama='Ajinomoto';
update items set nama='Chicken Powder', satuan='gr' where nama='Chicken Powder';
update items set nama='Minyak Samin 200 gr', satuan='carton' where nama='Minyak Samin';
update items set nama='Daun Bay', satuan='kg' where nama='Daun Bay';
update items set nama='Kayu Manis', satuan='kg' where nama='Kayu Manis';
update items set nama='Plastik Es 150s', satuan='pack' where nama='Plastik Es';
update items set nama='Bawang Bombay', satuan='kg' where nama='Bawang Bombay';
update items set nama='Kentang Keripik', satuan='kg' where nama='Keripik Kentang';
update items set nama='Kertas Kentang 100s', satuan='pack' where nama='Kertas Kentang';
update items set nama='Nugget Crispy Bubble', satuan='pack' where nama='Nugget';
update items set nama='Sambal Matah 500 gr', satuan='pack' where nama='Sambal Matah';
update items set nama='Kantong Plastik Pack UK 25 100s', satuan='pack' where nama='Plastik Kemasan uk. 25';
update items set nama='Kantong Plastik Pex 35', satuan='pack' where nama='Plastik Kemasan uk. 35';
update items set nama='Mainan Kids Meal', satuan='pcs' where nama='Mainan';
update items set nama='Cup Soup Almaz', satuan='pack' where nama='Cup Sup';
update items set nama='Pasta Cheese', satuan='pack' where nama='Pasta';
update items set nama='Garlic Mayo', satuan='pack' where nama='Garlic';
update items set nama='Japanese Curry', satuan='gr' where nama='Curry';
update items set nama='Saus Tomat Sachet', satuan='pack' where nama='Sauce Tomat';
update items set nama='Tepung Bumbu Ori', satuan='kg' where nama='Tepung Original';
update items set nama='Kayu Pengasapan', satuan='pack' where nama='Kayu';
