-- =========================================================
-- MIGRATION: Master data produk (dari template Stock Opname DC B)
-- Dipake buat auto-lengkapin Product Code / Category / Sub Category
-- pas export Excel, dicocokin lewat nama produk.
-- =========================================================

create table if not exists master_produk (
  id uuid primary key default gen_random_uuid(),
  nama text not null,
  kode_produk text,
  kategori text,
  sub_kategori text,
  satuan text,
  created_at timestamptz default now()
);

alter table master_produk enable row level security;
create policy "allow all master_produk" on master_produk for all using (true) with check (true);

create index if not exists idx_master_produk_nama on master_produk (lower(nama));

insert into master_produk (nama, kode_produk, kategori, sub_kategori, satuan) values
('Air Mineral 330ml', NULL, 'Food', 'Water/RTD', 'carton'),
('Air Mineral 600ml', NULL, 'Non-Food', 'Water/RTD', 'carton'),
('Ajinomoto 1 kg', 'A011001', 'Food', 'Spice', 'pack'),
('Alumunium Foil Jumbo', NULL, 'Non-Food', 'Accessories', 'Roll'),
('Alumunium Foil Super Jumbo', NULL, 'Non-Food', 'Packaging', 'Roll'),
('Apron', NULL, 'Non-Food', 'Accessories', 'pcs'),
('Ayam Crispy Almaz 8s', NULL, 'Food', 'Chicken', 'pack'),
('Ayam Crispy Almaz 9s', NULL, 'Food', 'Chicken', 'pack'),
('Ayam Hot Almaz 8s', 'A002002', 'Food', 'Chicken', 'pack'),
('Ayam Hot Almaz 9s', 'A002003', 'Food', 'Chicken', 'pack'),
('Ayam Karkas 6-7', 'A002004', 'Food', 'Chicken', 'pack'),
('Ayam Karkas 7-8', 'A002005', 'Food', 'Chicken', 'pcs'),
('Ayam Karkas > 1kg', 'A002006', 'Food', 'Chicken', 'pack'),
('Ayam Ori Almaz 8s', 'A002007', 'Food', 'Chicken', 'pack'),
('Ayam Panggang', 'A002009', 'Non-Food', 'Chicken', 'pack'),
('Ayam Rempah', 'A002010', 'Non-Food', 'Chicken', 'pack'),
('Ayam Ungkep Campur', 'A002011', 'Non-Food', 'Chicken', 'pack'),
('Ayam Ungkep Paha', 'A002012', 'Non-Food', 'Chicken', 'pack'),
('Balon Abuya', 'B008002', 'Non-Food', 'Merchandise', 'pcs'),
('Balon Almaz', NULL, 'Non-Food', 'Merchandise', 'pack'),
('Balon Kids', NULL, 'Non-Food', 'Merchandise', 'pack'),
('Basket Fryer', 'B007002', 'Non-Food', 'Nampan', 'pcs'),
('Bawang Bombay', NULL, 'Food', 'Vegetables', 'kg'),
('Bawang Putih Bubuk', 'A006002', 'Food', 'Vegetables', 'kg'),
('Bawang Putih Cutting', NULL, 'Food', 'Spice', 'kg'),
('Beef Patties', 'A004001', 'Food', 'Petties', 'pcs'),
('Beras Kebuli', 'A013001', 'Non-Food', 'Rice', 'ltr'),
('Beras Putih', 'A013002', 'Food', 'Rice', 'kg'),
('Boake 500 gr', NULL, 'Food', 'Powder', 'pcs'),
('Box Almaz', 'B001001', 'Non-Food', 'Box', 'carton'),
('Box Almaz Jumbo', 'B001002', 'Non-Food', 'Box', 'carton'),
('Box Almaz Special Edition', NULL, 'Non-Food', 'Box', 'carton'),
('Box Nampan Besar', NULL, 'Non-Food', 'Nampan', 'pcs'),
('Box Nampan Kecil', 'B007003', 'Non-Food', 'Nampan', 'pcs'),
('Box Segi 6', NULL, 'Non-Food', 'Packaging', 'pcs'),
('Box Take Away', 'B001003', 'Non-Food', 'Box', 'carton'),
('Box Take Away Premium', 'B001004', 'Non-Food', 'Box', 'pcs'),
('Bubuk Ice Cream Coklat 1Kg', 'A014001', 'Food', 'Powder', 'pack'),
('Bubuk Ice Cream Vanilla 1 Kg', 'A014002', 'Food', 'Powder', 'pack'),
('Bumbu Ayam Panggang (Lama)', 'A011002', 'Food', 'Spice', 'pack'),
('Bumbu Ayam Rempah (Lama)', 'A011003', 'Food', 'Spice', 'pack'),
('Bumbu Kebuli', 'A011004', 'Food', 'Spice', 'pcs'),
('Bumbu Marinasi', 'A011005', 'Food', 'Spice', 'kg'),
('Bumbu Marinasi Ayam Crispy', NULL, 'Food', 'Spice', 'kg'),
('Cayenne Powder', NULL, 'Food', 'Powder', 'kg'),
('CCTV', NULL, 'Non-Food', 'Aset', 'pcs'),
('Cengkeh', NULL, 'Food', 'Powder', 'kg'),
('Cengkeh Bubuk', NULL, 'Food', 'Powder', 'kg'),
('Chicken Katsu', 'A003001', 'Food', 'Frozen Food', 'pcs'),
('Chicken Petties', 'A004002', 'Food', 'Petties', 'pcs'),
('Chicken Powder', NULL, 'Food', 'Powder', 'gr'),
('Chocomilk Powder DLFR', NULL, 'Food', 'Powder', 'pack'),
('Cimory Cokelat Almond', 'A014010', 'Food', 'Powder', 'pcs'),
('Cool Time 350ml', NULL, 'Non-Food', 'Chicken', 'carton'),
('Country Choice Orange 1 ltr', NULL, 'Food', 'Water/RTD', 'ltr'),
('Cup Ice Cream', 'B002001', 'Non-Food', 'Cup', 'pack'),
('Cup Sambal 25 gr', 'B002004', 'Non-Food', 'Cup', 'pcs'),
('Cup Sambal 35 ml', NULL, 'Non-Food', 'Packaging', 'pack'),
('Cup Soup Almaz', 'B002002', 'Non-Food', 'Cup', 'pack'),
('Daging Kambing', 'A015001', 'Food', 'Lamb', 'gr'),
('Daun Bay', NULL, 'Food', 'Leaf', 'kg'),
('Daun Jeruk', NULL, 'Food', 'Spice', 'kg'),
('Delisa Hot Lava', 'A001001', 'Food', 'Sauce', 'pack'),
('Fruit Tea Botol', NULL, 'Non-Food', 'Water/RTD', 'carton'),
('Garam 250 gr', NULL, 'Food', 'Spice', 'pack'),
('Garlic Mayo', 'A001002', 'Food', 'Sauce', 'pack'),
('Gelas Cup Almaz', 'B002003', 'Non-Food', 'Cup', 'pack'),
('Japanese Curry', NULL, 'Food', 'Sauce', 'gr'),
('Jaring Polynet', NULL, 'Non-Food', 'Accessories', 'Roll'),
('Jinten', NULL, 'Food', 'Spice', 'kg'),
('Jinten Bubuk', NULL, 'Food', 'Powder', 'kg'),
('Kambing', 'A015002', 'Non-Food', 'Lamb', 'pcs'),
('Kantong Plastik Pack UK 25 100s', NULL, 'Non-Food', 'Plastic bag', 'pack'),
('Kantong Plastik Pex 35', 'B010001', 'Non-Food', 'Plastic bag', 'pack'),
('Kapulaga Hijau Bubuk', NULL, 'Food', 'Powder', 'kg'),
('Kapulaga Hijau Butir', NULL, 'Food', 'Spice', 'kg'),
('Kardus Big Order', NULL, 'Non-Food', 'Packaging', 'pcs'),
('Kayu Manis', 'A006005', 'Food', 'Vegetables', 'kg'),
('Kayu Pengasapan', 'B013001', 'Non-Food', 'Accessories', 'pack'),
('Kebab Beef Abuya', NULL, 'Food', 'Meat', 'pack'),
('Keju Prochiz Melt', 'A019001', 'Food', 'Cheese', 'pcs'),
('Keju Prochiz Melt 10pcs', 'A019002', 'Food', 'Cheese', 'pcs'),
('Kembang Lawang Bubuk', NULL, 'Food', 'Powder', 'kg'),
('Kentang Keripik', 'A011006', 'Non-Food', 'Spice', 'kg'),
('Kentang Straight Cut', 'A003002', 'Food', 'Frozen Food', 'kg'),
('Kentang Straight Cut Skin-On', NULL, 'Food', 'Frozen Food', 'kg'),
('Kertas Filter Oil Besar', 'B013002', 'Non-Food', 'Accessories', 'pcs'),
('Kertas Filter Oil Kecil', 'B013004', 'Non-Food', 'Accessories', 'pcs'),
('Kertas Kentang 100s', 'B006001', 'Non-Food', 'Paperbag', 'pack'),
('Kertas Nasi 1000s', 'B016001', 'Non-Food', 'Rice Paper', 'pack'),
('Kertas Nasi Kebuli Abuya 1000s', NULL, 'Non-Food', 'Rice Paper', 'pack'),
('Kertas Nasi Special', NULL, 'Non-Food', 'Rice Paper', 'pcs'),
('Kertas Struk Thermal', NULL, 'Non-Food', 'Accessories', 'Roll'),
('Kismis', NULL, 'Food', 'Fruit', 'kg'),
('Koepoe B. Putih Bubuk', 'A014005', 'Food', 'Powder', 'kg'),
('Koepoe Jinten Bubuk', 'A014006', 'Food', 'Powder', 'kg'),
('Koepoe Kare Bubuk', 'A014007', 'Food', 'Powder', 'kg'),
('Kopoe-Kopoe Pewarna Kuning Muda', 'A014008', 'Food', 'Powder', 'pcs'),
('Kunyit Bubuk', NULL, 'Food', 'Powder', 'kg'),
('Kurma Medjool', 'A007001', 'Food', 'Fruit', 'kg'),
('Kurma Sauce', NULL, 'Food', 'Sauce', 'carton'),
('Lada Hitam Bubuk', NULL, 'Food', 'Powder', 'kg'),
('Lemon Tea Powder', NULL, 'Food', 'Powder', 'pack'),
('Lid Cup Ice Cream 5oz', 'B004001', 'Non-Food', 'Lid', 'pack'),
('Lid Paper Cup 8oz', 'B004002', 'Non-Food', 'Lid', 'pack'),
('Lid Sup Cup 8oz', 'B004003', 'Non-Food', 'Lid', 'pcs'),
('Mainan Kids Meal', NULL, 'Non-Food', 'Accessories', 'pcs'),
('Martabak Mesir', NULL, 'Non-Food', 'Bread', 'pcs'),
('Masako', 'A011007', 'Food', 'Spice', 'kg'),
('Max Food Chocolate D257A 1 kg', NULL, 'Food', 'Powder', 'pack'),
('Max Food Sofice Vanilla D295 1 kg', NULL, 'Food', 'Powder', 'pack'),
('Mayonaise 1kg', 'A001003', 'Food', 'Sauce', 'gr'),
('MEMORY CARD', NULL, 'Non-Food', 'Aset', 'pcs'),
('Minyak Beku 15kg', 'A008001', 'Non-Food', 'Oil', 'carton'),
('Minyak Samin 200 gr', NULL, 'Food', 'Oil', 'carton'),
('Minyak Tropical Botol 1 Ltr', NULL, 'Food', 'Oil', 'pcs'),
('Minyak Tropical Botol 2 Ltr', 'A008003', 'Non-Food', 'Oil', 'pcs'),
('Mix Vegetable', 'A003004', 'Food', 'Frozen Food', 'pack'),
('Nampan Besar', NULL, 'Non-Food', 'Nampan', 'pcs'),
('Nampan Kecil', NULL, 'Non-Food', 'Nampan', 'pcs'),
('Nasi Kebuli', 'A013003', 'Non-Food', 'Rice', 'porsi'),
('Nipis Madu 330ml', NULL, 'Food', 'Chicken', 'pcs'),
('Nugget Crispy Bubble', 'A003005', 'Food', 'Frozen Food', 'pack'),
('Oregano', NULL, 'Food', 'Spice', 'kg'),
('Paper Bag Burger', 'B006002', 'Non-Food', 'Paperbag', 'pack'),
('Paper Bowl Almaz', 'B006003', 'Non-Food', 'Paperbag', 'pack'),
('Paper Bowl Kids 16 oz Set', NULL, 'Non-Food', 'Packaging', 'pcs'),
('Paper Cup 8oz', 'B006004', 'Non-Food', 'Paperbag', 'pack'),
('Paprika Bubuk', NULL, 'Food', 'Powder', 'kg'),
('Pasta Cheese', NULL, 'Food', 'Cheese', 'pack'),
('Pewarna Marinasi Idacol Sunset Yellow', NULL, 'Food', 'Powder', 'pack'),
('Piring Emas Besar', NULL, 'Non-Food', 'Bowl', 'pcs'),
('Piring Saji Plastik', 'B003001', 'Non-Food', 'Bowl', 'pcs'),
('Plastik Es 150s', NULL, 'Non-Food', 'Plastic bag', 'pack'),
('Plastik Klip Sambal', NULL, 'Non-Food', 'Plastic bag', 'pack'),
('Plastik Merah Besar', NULL, 'Non-Food', 'Plastic bag', 'pack'),
('Plastik Merah Kecil', NULL, 'Non-Food', 'Plastic bag', 'pack'),
('Plastik Putih Kecil', NULL, 'Non-Food', 'Plastic bag', 'pack'),
('Plastik Putih Sedang', NULL, 'Non-Food', 'Plastic bag', 'pack'),
('Plastik Sampah', NULL, 'Non-Food', 'Plastic bag', 'pack'),
('Plastik Sampah uk 90x120', NULL, 'Non-Food', 'Plastic bag', 'pack'),
('Plastik Vacuum New', NULL, 'Food', 'Plastic bag', 'pcs'),
('Polaris Kaleng', NULL, 'Food', 'Water/RTD', 'pcs'),
('Roti Burger', 'A005001', 'Food', 'Bread', 'pcs'),
('Roti Cane', NULL, 'Non-Food', 'Bread', 'pcs'),
('Safron Orange', NULL, 'Food', 'Powder', 'pcs'),
('Safron Yellow', NULL, 'Food', 'Powder', 'pcs'),
('Sambal 500gr (new)', 'A001004', 'Non-Food', 'Sauce', 'pack'),
('Sambal Bawang Sachet', NULL, 'Food', 'Sauce', 'carton'),
('Sambal Matah 500 gr', NULL, 'Food', 'Sauce', 'pack'),
('Samosa', NULL, 'Food', 'Frozen Food', 'pcs'),
('Sarung Tangan Plastik', NULL, 'Non-Food', 'Accessories', 'pack'),
('Saus BBQ', 'A001005', 'Food', 'Sauce', 'pack'),
('Saus Black Pepper', 'A001006', 'Food', 'Sauce', 'pack'),
('Saus Sambal Sachet', 'A001007', 'Food', 'Sauce', 'pack'),
('Saus Tomat Sachet', 'A001008', 'Food', 'Sauce', 'pack'),
('Scrambeled Egg', NULL, 'Food', 'Sauce', 'gr'),
('Sealer Cup', 'B009001', 'Non-Food', 'Equipment', 'Roll'),
('Sendok Bowl Almaz', 'B005001', 'Non-Food', 'Spoon', 'pack'),
('Sitrun', NULL, 'Non-Food', 'Equipment', 'pcs'),
('Spready Orange 2kg', 'A019003', 'Food', 'Cheese', 'pack'),
('Styrofoam Box', NULL, 'Non-Food', 'Box', 'pcs'),
('Sunlight Refil 105ml', NULL, 'Non-Food', 'Equipment', 'pcs'),
('Suntikan Marinasi', NULL, 'Non-Food', 'Grand Opening', 'pcs'),
('Sup Krim Ayam', 'A014009', 'Food', 'Powder', 'pack'),
('Susu Tujuh Kurma', NULL, 'Non-Food', 'Water/RTD', 'carton'),
('Susu UHT Full Cream', NULL, 'Food', 'Milk', 'carton'),
('Susu UHT Kids', NULL, 'Food', 'Water/RTD', 'pcs'),
('Tebs Sparkling Mix Tea 330ml', NULL, 'Food', 'Water/RTD', 'carton'),
('Tebs Sparklling Lychee 300ml', NULL, 'Food', 'Water/RTD', 'carton'),
('Teh Botal Kotak 250ml', 'A012003', 'Food', 'Water/RTD', 'pcs'),
('Teh Botol 1Lt', 'A012004', 'Food', 'Water/RTD', 'carton'),
('Teh Kemasan Botol', NULL, 'Non-Food', 'Water/RTD', 'carton'),
('Teh Pandan Selasih', 'A012005', 'Food', 'Water/RTD', 'pack'),
('Tempat Sampah', NULL, 'Non-Food', 'Grand Opening', 'pcs'),
('Tepung Bumbu HOT', 'A009001', 'Food', 'Flour', 'kg'),
('Tepung Bumbu Ori', 'A009002', 'Food', 'Flour', 'kg'),
('Tepung Cakra', 'A009003', 'Food', 'Flour', 'ball'),
('Tiang Balon', NULL, 'Non-Food', 'Aset', 'pcs'),
('Tissue Makan', 'B012001', 'Non-Food', 'Tissue', 'pack'),
('Tissue Roll Toilet', 'B012002', 'Non-Food', 'Tissue', 'carton'),
('Tissue Wastafel', 'B012003', 'Non-Food', 'Tissue', 'carton'),
('Tote Bag Almaz', NULL, 'Non-Food', 'Merchandise', 'pcs'),
('Transportation Cost', NULL, 'Non-Food', 'Fee', 'pcs'),
('Wipol', NULL, 'Non-Food', 'Equipment', 'pcs'),
('Wrapping Film Jumbo', NULL, 'Non-Food', 'Wrapping Film', 'Roll');
